### ISSUE TITLE
App crashing sometimes on the repo details screen

### ISSUE THREAD

**Issue by mustafa01ali** [forkhubs/android#679]
I am seeing this crash randomly when I navigate to the repository details screen, doesn't happen every time.

```java
01-15 02:15:44.088    3674-3674/com.github.mobile W/nalizableReferenceQueue﹕ Could not load Finalizer in its own class loader. Loading Finalizer in the current class loader instead. As a result, you will not be able to garbage collect this class loader. To support reclaiming this class loader, either resolve the underlying issue, or move Google Collections to your system class path.
    java.io.FileNotFoundException: com/google/inject/internal/util/$Finalizer.class
            at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:269)
            at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:253)
            at com.google.inject.internal.util.$FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:175)
            at com.google.inject.internal.util.$FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:100)
            at com.google.inject.internal.util.$MapMaker$QueueHolder.<clinit>(MapMaker.java:787)
            at com.google.inject.internal.util.$MapMaker$WeakEntry.<init>(MapMaker.java:946)
            at com.google.inject.internal.util.$MapMaker$Strength$1.newEntry(MapMaker.java:312)
            at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:498)
            at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:419)
            at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2029)
            at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:116)
            at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:180)
            at com.google.inject.Key.ensureIsBindingAnnotation(Key.java:366)
            at com.google.inject.Key.strategyFor(Key.java:338)
            at com.google.inject.Key.get(Key.java:272)
            at com.google.inject.internal.AbstractBindingBuilder.annotatedWithInternal(AbstractBindingBuilder.java:82)
            at com.google.inject.internal.ConstantBindingBuilderImpl.annotatedWith(ConstantBindingBuilderImpl.java:49)
            at roboguice.config.DefaultRoboModule.configure(DefaultRoboModule.java:117)
            at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
            at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
            at com.google.inject.spi.Elements.getElements(Elements.java:101)
            at com.google.inject.spi.Elements.getElements(Elements.java:78)
            at roboguice.RoboGuice.setBaseApplicationInjector(RoboGuice.java:83)
            at roboguice.RoboGuice.setBaseApplicationInjector(RoboGuice.java:139)
            at roboguice.RoboGuice.getBaseApplicationInjector(RoboGuice.java:59)
            at roboguice.RoboGuice.getInjector(RoboGuice.java:149)
            at com.github.mobile.ui.roboactivities.RoboActionBarActivity.onCreate(RoboActionBarActivity.java:42)
            at com.github.mobile.ui.BaseActivity.onCreate(BaseActivity.java:37)
            at com.github.mobile.ui.MainActivity.onCreate(MainActivity.java:61)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by fadils** [comment]
I will take a look at this soon.
Thanks.

**Comment by hzsweers** [comment]
I think this is another sign that we should strive to get off Roboguice. Going to close this for now though since the issue is a little stale, we can re-open if more people experience it.
