### ISSUE TITLE
Crash in gist's "all tab", NullPointerException

### ISSUE THREAD

**Issue by zhengxiaopeng** [forkhubs/android#775]
Commit 7bee3b232c876db7c9f80a753079b690b4db8927
   

![git](http://7tsy92.com1.z0.glb.clouddn.com/commit_7bee3b232c876db7c9f80a753079b690b4db8927.gif)
   

Log message:
``` brash
04-16 08:27:14.040: E/AndroidRuntime(2054): FATAL EXCEPTION: main
04-16 08:27:14.040: E/AndroidRuntime(2054): Process: com.github.mobile, PID: 2054
04-16 08:27:14.040: E/AndroidRuntime(2054): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.eclipse.egit.github.core.User.getAvatarUrl()' on a null object reference
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.mobile.util.AvatarLoader.getAvatarUrl(AvatarLoader.java:200)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.mobile.util.AvatarLoader.bind(AvatarLoader.java:159)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.mobile.ui.gist.GistListAdapter.update(GistListAdapter.java:91)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.mobile.ui.gist.GistListAdapter.update(GistListAdapter.java:37)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.kevinsawicki.wishlist.SingleTypeAdapter.update(SingleTypeAdapter.java:164)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at com.github.kevinsawicki.wishlist.SingleTypeAdapter.getView(SingleTypeAdapter.java:180)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.AbsListView.obtainView(AbsListView.java:2344)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.ListView.makeAndAddView(ListView.java:1864)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.ListView.fillSpecific(ListView.java:1344)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.ListView.layoutChildren(ListView.java:1651)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.View.layout(View.java:15596)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.view.ViewGroup.layout(ViewGroup.java:4966)
04-16 08:27:14.040: E/AndroidRuntime(2054): 	at android.widget.FrameLayout.layoutChildren(Fra
04-16 08:27:14.067: E/EGL_emulation(147): tid 147: eglCreateSyncKHR(1181): error 0x3004 (EGL_BAD_ATTRIBUTE)

```

**Comment by jonan** [comment]
This bug was introduced in https://github.com/forkhubs/android/pull/744.

I fixed it in https://github.com/jonan/ForkHub/commit/b8f57ba46f327b041f860ec38974e0298e5d00c9 but didn't update the PR. I'll fix it now.

**Comment by zhengxiaopeng** [comment]
@jonan Alright ，looking forward to your PR.
